# ***
# WARNING: Do not EDIT or MERGE this file, it is generated by packagespec.
# ***

LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_ID             := 00-base-c6cdf1b224722d2520e082320f2a71875913247c
LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_TYPE           := base
LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_BASE_LAYER     := 
LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_SOURCE_INCLUDE := 
LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_SOURCE_EXCLUDE := 
LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_CACHE_KEY_FILE := .buildcache/cache-keys/base-c6cdf1b224722d2520e082320f2a71875913247c
LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_ARCHIVE_FILE   := .buildcache/archives/00-base-c6cdf1b224722d2520e082320f2a71875913247c.tar.gz
$(eval $(call LAYER,$(LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_ID),$(LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_TYPE),$(LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_BASE_LAYER),$(LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_SOURCE_INCLUDE),$(LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_SOURCE_EXCLUDE),$(LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_CACHE_KEY_FILE),$(LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_ARCHIVE_FILE)))

LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_ID             := 01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812
LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_TYPE           := install-go
LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_BASE_LAYER     := 00-base-c6cdf1b224722d2520e082320f2a71875913247c
LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_SOURCE_INCLUDE := 
LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_SOURCE_EXCLUDE := 
LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_CACHE_KEY_FILE := .buildcache/cache-keys/install-go-f39f5d66161bdd79b182943a3accdd95510c4812
LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_ARCHIVE_FILE   := .buildcache/archives/01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812.tar.gz
$(eval $(call LAYER,$(LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_ID),$(LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_TYPE),$(LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_BASE_LAYER),$(LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_SOURCE_INCLUDE),$(LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_SOURCE_EXCLUDE),$(LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_CACHE_KEY_FILE),$(LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_ARCHIVE_FILE)))

LAYER_02-install-go-tools-c0f572164cd4805f2bcf77664d7e02c169682491_ID             := 02-install-go-tools-c0f572164cd4805f2bcf77664d7e02c169682491
LAYER_02-install-go-tools-c0f572164cd4805f2bcf77664d7e02c169682491_TYPE           := install-go-tools
LAYER_02-install-go-tools-c0f572164cd4805f2bcf77664d7e02c169682491_BASE_LAYER     := 01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812
LAYER_02-install-go-tools-c0f572164cd4805f2bcf77664d7e02c169682491_SOURCE_INCLUDE := 
LAYER_02-install-go-tools-c0f572164cd4805f2bcf77664d7e02c169682491_SOURCE_EXCLUDE := 
LAYER_02-install-go-tools-c0f572164cd4805f2bcf77664d7e02c169682491_CACHE_KEY_FILE := .buildcache/cache-keys/install-go-tools-c0f572164cd4805f2bcf77664d7e02c169682491
LAYER_02-install-go-tools-c0f572164cd4805f2bcf77664d7e02c169682491_ARCHIVE_FILE   := .buildcache/archives/02-install-go-tools-c0f572164cd4805f2bcf77664d7e02c169682491.tar.gz
$(eval $(call LAYER,$(LAYER_02-install-go-tools-c0f572164cd4805f2bcf77664d7e02c169682491_ID),$(LAYER_02-install-go-tools-c0f572164cd4805f2bcf77664d7e02c169682491_TYPE),$(LAYER_02-install-go-tools-c0f572164cd4805f2bcf77664d7e02c169682491_BASE_LAYER),$(LAYER_02-install-go-tools-c0f572164cd4805f2bcf77664d7e02c169682491_SOURCE_INCLUDE),$(LAYER_02-install-go-tools-c0f572164cd4805f2bcf77664d7e02c169682491_SOURCE_EXCLUDE),$(LAYER_02-install-go-tools-c0f572164cd4805f2bcf77664d7e02c169682491_CACHE_KEY_FILE),$(LAYER_02-install-go-tools-c0f572164cd4805f2bcf77664d7e02c169682491_ARCHIVE_FILE)))

LAYER_03-set-workdir-a8232400e220adcccbb9c45a41542b9497d0d21f_ID             := 03-set-workdir-a8232400e220adcccbb9c45a41542b9497d0d21f
LAYER_03-set-workdir-a8232400e220adcccbb9c45a41542b9497d0d21f_TYPE           := set-workdir
LAYER_03-set-workdir-a8232400e220adcccbb9c45a41542b9497d0d21f_BASE_LAYER     := 02-install-go-tools-c0f572164cd4805f2bcf77664d7e02c169682491
LAYER_03-set-workdir-a8232400e220adcccbb9c45a41542b9497d0d21f_SOURCE_INCLUDE := 
LAYER_03-set-workdir-a8232400e220adcccbb9c45a41542b9497d0d21f_SOURCE_EXCLUDE := 
LAYER_03-set-workdir-a8232400e220adcccbb9c45a41542b9497d0d21f_CACHE_KEY_FILE := .buildcache/cache-keys/set-workdir-a8232400e220adcccbb9c45a41542b9497d0d21f
LAYER_03-set-workdir-a8232400e220adcccbb9c45a41542b9497d0d21f_ARCHIVE_FILE   := .buildcache/archives/03-set-workdir-a8232400e220adcccbb9c45a41542b9497d0d21f.tar.gz
$(eval $(call LAYER,$(LAYER_03-set-workdir-a8232400e220adcccbb9c45a41542b9497d0d21f_ID),$(LAYER_03-set-workdir-a8232400e220adcccbb9c45a41542b9497d0d21f_TYPE),$(LAYER_03-set-workdir-a8232400e220adcccbb9c45a41542b9497d0d21f_BASE_LAYER),$(LAYER_03-set-workdir-a8232400e220adcccbb9c45a41542b9497d0d21f_SOURCE_INCLUDE),$(LAYER_03-set-workdir-a8232400e220adcccbb9c45a41542b9497d0d21f_SOURCE_EXCLUDE),$(LAYER_03-set-workdir-a8232400e220adcccbb9c45a41542b9497d0d21f_CACHE_KEY_FILE),$(LAYER_03-set-workdir-a8232400e220adcccbb9c45a41542b9497d0d21f_ARCHIVE_FILE)))

LAYER_04-install-yarn-d8f06ad14416849abce755043d691e698bd16d6a_ID             := 04-install-yarn-d8f06ad14416849abce755043d691e698bd16d6a
LAYER_04-install-yarn-d8f06ad14416849abce755043d691e698bd16d6a_TYPE           := install-yarn
LAYER_04-install-yarn-d8f06ad14416849abce755043d691e698bd16d6a_BASE_LAYER     := 03-set-workdir-a8232400e220adcccbb9c45a41542b9497d0d21f
LAYER_04-install-yarn-d8f06ad14416849abce755043d691e698bd16d6a_SOURCE_INCLUDE := 
LAYER_04-install-yarn-d8f06ad14416849abce755043d691e698bd16d6a_SOURCE_EXCLUDE := 
LAYER_04-install-yarn-d8f06ad14416849abce755043d691e698bd16d6a_CACHE_KEY_FILE := .buildcache/cache-keys/install-yarn-d8f06ad14416849abce755043d691e698bd16d6a
LAYER_04-install-yarn-d8f06ad14416849abce755043d691e698bd16d6a_ARCHIVE_FILE   := .buildcache/archives/04-install-yarn-d8f06ad14416849abce755043d691e698bd16d6a.tar.gz
$(eval $(call LAYER,$(LAYER_04-install-yarn-d8f06ad14416849abce755043d691e698bd16d6a_ID),$(LAYER_04-install-yarn-d8f06ad14416849abce755043d691e698bd16d6a_TYPE),$(LAYER_04-install-yarn-d8f06ad14416849abce755043d691e698bd16d6a_BASE_LAYER),$(LAYER_04-install-yarn-d8f06ad14416849abce755043d691e698bd16d6a_SOURCE_INCLUDE),$(LAYER_04-install-yarn-d8f06ad14416849abce755043d691e698bd16d6a_SOURCE_EXCLUDE),$(LAYER_04-install-yarn-d8f06ad14416849abce755043d691e698bd16d6a_CACHE_KEY_FILE),$(LAYER_04-install-yarn-d8f06ad14416849abce755043d691e698bd16d6a_ARCHIVE_FILE)))

LAYER_05-ui-dependencies-e32637cb0eddbb636aaba43367db03df2b6c8228_ID             := 05-ui-dependencies-e32637cb0eddbb636aaba43367db03df2b6c8228
LAYER_05-ui-dependencies-e32637cb0eddbb636aaba43367db03df2b6c8228_TYPE           := ui-dependencies
LAYER_05-ui-dependencies-e32637cb0eddbb636aaba43367db03df2b6c8228_BASE_LAYER     := 04-install-yarn-d8f06ad14416849abce755043d691e698bd16d6a
LAYER_05-ui-dependencies-e32637cb0eddbb636aaba43367db03df2b6c8228_SOURCE_INCLUDE := ui/package.json ui/yarn.lock
LAYER_05-ui-dependencies-e32637cb0eddbb636aaba43367db03df2b6c8228_SOURCE_EXCLUDE := 
LAYER_05-ui-dependencies-e32637cb0eddbb636aaba43367db03df2b6c8228_CACHE_KEY_FILE := .buildcache/cache-keys/ui-dependencies-e32637cb0eddbb636aaba43367db03df2b6c8228
LAYER_05-ui-dependencies-e32637cb0eddbb636aaba43367db03df2b6c8228_ARCHIVE_FILE   := .buildcache/archives/05-ui-dependencies-e32637cb0eddbb636aaba43367db03df2b6c8228.tar.gz
$(eval $(call LAYER,$(LAYER_05-ui-dependencies-e32637cb0eddbb636aaba43367db03df2b6c8228_ID),$(LAYER_05-ui-dependencies-e32637cb0eddbb636aaba43367db03df2b6c8228_TYPE),$(LAYER_05-ui-dependencies-e32637cb0eddbb636aaba43367db03df2b6c8228_BASE_LAYER),$(LAYER_05-ui-dependencies-e32637cb0eddbb636aaba43367db03df2b6c8228_SOURCE_INCLUDE),$(LAYER_05-ui-dependencies-e32637cb0eddbb636aaba43367db03df2b6c8228_SOURCE_EXCLUDE),$(LAYER_05-ui-dependencies-e32637cb0eddbb636aaba43367db03df2b6c8228_CACHE_KEY_FILE),$(LAYER_05-ui-dependencies-e32637cb0eddbb636aaba43367db03df2b6c8228_ARCHIVE_FILE)))

LAYER_06-build-ui-ee1bca933dae6187a0a3358d4b3a17b36d4b6fde_ID             := 06-build-ui-ee1bca933dae6187a0a3358d4b3a17b36d4b6fde
LAYER_06-build-ui-ee1bca933dae6187a0a3358d4b3a17b36d4b6fde_TYPE           := build-ui
LAYER_06-build-ui-ee1bca933dae6187a0a3358d4b3a17b36d4b6fde_BASE_LAYER     := 05-ui-dependencies-e32637cb0eddbb636aaba43367db03df2b6c8228
LAYER_06-build-ui-ee1bca933dae6187a0a3358d4b3a17b36d4b6fde_SOURCE_INCLUDE := ui/
LAYER_06-build-ui-ee1bca933dae6187a0a3358d4b3a17b36d4b6fde_SOURCE_EXCLUDE := 
LAYER_06-build-ui-ee1bca933dae6187a0a3358d4b3a17b36d4b6fde_CACHE_KEY_FILE := .buildcache/cache-keys/build-ui-ee1bca933dae6187a0a3358d4b3a17b36d4b6fde
LAYER_06-build-ui-ee1bca933dae6187a0a3358d4b3a17b36d4b6fde_ARCHIVE_FILE   := .buildcache/archives/06-build-ui-ee1bca933dae6187a0a3358d4b3a17b36d4b6fde.tar.gz
$(eval $(call LAYER,$(LAYER_06-build-ui-ee1bca933dae6187a0a3358d4b3a17b36d4b6fde_ID),$(LAYER_06-build-ui-ee1bca933dae6187a0a3358d4b3a17b36d4b6fde_TYPE),$(LAYER_06-build-ui-ee1bca933dae6187a0a3358d4b3a17b36d4b6fde_BASE_LAYER),$(LAYER_06-build-ui-ee1bca933dae6187a0a3358d4b3a17b36d4b6fde_SOURCE_INCLUDE),$(LAYER_06-build-ui-ee1bca933dae6187a0a3358d4b3a17b36d4b6fde_SOURCE_EXCLUDE),$(LAYER_06-build-ui-ee1bca933dae6187a0a3358d4b3a17b36d4b6fde_CACHE_KEY_FILE),$(LAYER_06-build-ui-ee1bca933dae6187a0a3358d4b3a17b36d4b6fde_ARCHIVE_FILE)))

LAYER_07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a_ID             := 07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a
LAYER_07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a_TYPE           := build-static-assets
LAYER_07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a_BASE_LAYER     := 06-build-ui-ee1bca933dae6187a0a3358d4b3a17b36d4b6fde
LAYER_07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a_SOURCE_INCLUDE := Makefile
LAYER_07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a_SOURCE_EXCLUDE := 
LAYER_07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a_CACHE_KEY_FILE := .buildcache/cache-keys/build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a
LAYER_07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a_ARCHIVE_FILE   := .buildcache/archives/07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a.tar.gz
$(eval $(call LAYER,$(LAYER_07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a_ID),$(LAYER_07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a_TYPE),$(LAYER_07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a_BASE_LAYER),$(LAYER_07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a_SOURCE_INCLUDE),$(LAYER_07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a_SOURCE_EXCLUDE),$(LAYER_07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a_CACHE_KEY_FILE),$(LAYER_07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-09d209869ea8d7ec24075af621821444526443f4_ID             := 08-warm-go-build-vendor-cache-09d209869ea8d7ec24075af621821444526443f4
LAYER_08-warm-go-build-vendor-cache-09d209869ea8d7ec24075af621821444526443f4_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-09d209869ea8d7ec24075af621821444526443f4_BASE_LAYER     := 07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a
LAYER_08-warm-go-build-vendor-cache-09d209869ea8d7ec24075af621821444526443f4_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-09d209869ea8d7ec24075af621821444526443f4_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-09d209869ea8d7ec24075af621821444526443f4_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-09d209869ea8d7ec24075af621821444526443f4
LAYER_08-warm-go-build-vendor-cache-09d209869ea8d7ec24075af621821444526443f4_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-09d209869ea8d7ec24075af621821444526443f4.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-09d209869ea8d7ec24075af621821444526443f4_ID),$(LAYER_08-warm-go-build-vendor-cache-09d209869ea8d7ec24075af621821444526443f4_TYPE),$(LAYER_08-warm-go-build-vendor-cache-09d209869ea8d7ec24075af621821444526443f4_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-09d209869ea8d7ec24075af621821444526443f4_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-09d209869ea8d7ec24075af621821444526443f4_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-09d209869ea8d7ec24075af621821444526443f4_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-09d209869ea8d7ec24075af621821444526443f4_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-1396b381f7ea7b775f15a067617c7484766d073b_ID             := 08-warm-go-build-vendor-cache-1396b381f7ea7b775f15a067617c7484766d073b
LAYER_08-warm-go-build-vendor-cache-1396b381f7ea7b775f15a067617c7484766d073b_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-1396b381f7ea7b775f15a067617c7484766d073b_BASE_LAYER     := 07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a
LAYER_08-warm-go-build-vendor-cache-1396b381f7ea7b775f15a067617c7484766d073b_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-1396b381f7ea7b775f15a067617c7484766d073b_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-1396b381f7ea7b775f15a067617c7484766d073b_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-1396b381f7ea7b775f15a067617c7484766d073b
LAYER_08-warm-go-build-vendor-cache-1396b381f7ea7b775f15a067617c7484766d073b_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-1396b381f7ea7b775f15a067617c7484766d073b.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-1396b381f7ea7b775f15a067617c7484766d073b_ID),$(LAYER_08-warm-go-build-vendor-cache-1396b381f7ea7b775f15a067617c7484766d073b_TYPE),$(LAYER_08-warm-go-build-vendor-cache-1396b381f7ea7b775f15a067617c7484766d073b_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-1396b381f7ea7b775f15a067617c7484766d073b_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-1396b381f7ea7b775f15a067617c7484766d073b_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-1396b381f7ea7b775f15a067617c7484766d073b_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-1396b381f7ea7b775f15a067617c7484766d073b_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-23a6c6f7a369ed9e9975e4e24f3c8f01c83ea162_ID             := 08-warm-go-build-vendor-cache-23a6c6f7a369ed9e9975e4e24f3c8f01c83ea162
LAYER_08-warm-go-build-vendor-cache-23a6c6f7a369ed9e9975e4e24f3c8f01c83ea162_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-23a6c6f7a369ed9e9975e4e24f3c8f01c83ea162_BASE_LAYER     := 07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a
LAYER_08-warm-go-build-vendor-cache-23a6c6f7a369ed9e9975e4e24f3c8f01c83ea162_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-23a6c6f7a369ed9e9975e4e24f3c8f01c83ea162_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-23a6c6f7a369ed9e9975e4e24f3c8f01c83ea162_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-23a6c6f7a369ed9e9975e4e24f3c8f01c83ea162
LAYER_08-warm-go-build-vendor-cache-23a6c6f7a369ed9e9975e4e24f3c8f01c83ea162_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-23a6c6f7a369ed9e9975e4e24f3c8f01c83ea162.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-23a6c6f7a369ed9e9975e4e24f3c8f01c83ea162_ID),$(LAYER_08-warm-go-build-vendor-cache-23a6c6f7a369ed9e9975e4e24f3c8f01c83ea162_TYPE),$(LAYER_08-warm-go-build-vendor-cache-23a6c6f7a369ed9e9975e4e24f3c8f01c83ea162_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-23a6c6f7a369ed9e9975e4e24f3c8f01c83ea162_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-23a6c6f7a369ed9e9975e4e24f3c8f01c83ea162_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-23a6c6f7a369ed9e9975e4e24f3c8f01c83ea162_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-23a6c6f7a369ed9e9975e4e24f3c8f01c83ea162_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-2c63ea8cc70c02b080c15ea409277e4444eda586_ID             := 08-warm-go-build-vendor-cache-2c63ea8cc70c02b080c15ea409277e4444eda586
LAYER_08-warm-go-build-vendor-cache-2c63ea8cc70c02b080c15ea409277e4444eda586_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-2c63ea8cc70c02b080c15ea409277e4444eda586_BASE_LAYER     := 07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a
LAYER_08-warm-go-build-vendor-cache-2c63ea8cc70c02b080c15ea409277e4444eda586_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-2c63ea8cc70c02b080c15ea409277e4444eda586_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-2c63ea8cc70c02b080c15ea409277e4444eda586_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-2c63ea8cc70c02b080c15ea409277e4444eda586
LAYER_08-warm-go-build-vendor-cache-2c63ea8cc70c02b080c15ea409277e4444eda586_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-2c63ea8cc70c02b080c15ea409277e4444eda586.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-2c63ea8cc70c02b080c15ea409277e4444eda586_ID),$(LAYER_08-warm-go-build-vendor-cache-2c63ea8cc70c02b080c15ea409277e4444eda586_TYPE),$(LAYER_08-warm-go-build-vendor-cache-2c63ea8cc70c02b080c15ea409277e4444eda586_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-2c63ea8cc70c02b080c15ea409277e4444eda586_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-2c63ea8cc70c02b080c15ea409277e4444eda586_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-2c63ea8cc70c02b080c15ea409277e4444eda586_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-2c63ea8cc70c02b080c15ea409277e4444eda586_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-4d2cd97c46a8cbe60b8b278a7c1abead3418dbf4_ID             := 08-warm-go-build-vendor-cache-4d2cd97c46a8cbe60b8b278a7c1abead3418dbf4
LAYER_08-warm-go-build-vendor-cache-4d2cd97c46a8cbe60b8b278a7c1abead3418dbf4_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-4d2cd97c46a8cbe60b8b278a7c1abead3418dbf4_BASE_LAYER     := 07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a
LAYER_08-warm-go-build-vendor-cache-4d2cd97c46a8cbe60b8b278a7c1abead3418dbf4_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-4d2cd97c46a8cbe60b8b278a7c1abead3418dbf4_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-4d2cd97c46a8cbe60b8b278a7c1abead3418dbf4_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-4d2cd97c46a8cbe60b8b278a7c1abead3418dbf4
LAYER_08-warm-go-build-vendor-cache-4d2cd97c46a8cbe60b8b278a7c1abead3418dbf4_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-4d2cd97c46a8cbe60b8b278a7c1abead3418dbf4.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-4d2cd97c46a8cbe60b8b278a7c1abead3418dbf4_ID),$(LAYER_08-warm-go-build-vendor-cache-4d2cd97c46a8cbe60b8b278a7c1abead3418dbf4_TYPE),$(LAYER_08-warm-go-build-vendor-cache-4d2cd97c46a8cbe60b8b278a7c1abead3418dbf4_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-4d2cd97c46a8cbe60b8b278a7c1abead3418dbf4_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-4d2cd97c46a8cbe60b8b278a7c1abead3418dbf4_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-4d2cd97c46a8cbe60b8b278a7c1abead3418dbf4_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-4d2cd97c46a8cbe60b8b278a7c1abead3418dbf4_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-50ce464b740a02700915a5b205af7573ab133b89_ID             := 08-warm-go-build-vendor-cache-50ce464b740a02700915a5b205af7573ab133b89
LAYER_08-warm-go-build-vendor-cache-50ce464b740a02700915a5b205af7573ab133b89_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-50ce464b740a02700915a5b205af7573ab133b89_BASE_LAYER     := 07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a
LAYER_08-warm-go-build-vendor-cache-50ce464b740a02700915a5b205af7573ab133b89_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-50ce464b740a02700915a5b205af7573ab133b89_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-50ce464b740a02700915a5b205af7573ab133b89_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-50ce464b740a02700915a5b205af7573ab133b89
LAYER_08-warm-go-build-vendor-cache-50ce464b740a02700915a5b205af7573ab133b89_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-50ce464b740a02700915a5b205af7573ab133b89.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-50ce464b740a02700915a5b205af7573ab133b89_ID),$(LAYER_08-warm-go-build-vendor-cache-50ce464b740a02700915a5b205af7573ab133b89_TYPE),$(LAYER_08-warm-go-build-vendor-cache-50ce464b740a02700915a5b205af7573ab133b89_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-50ce464b740a02700915a5b205af7573ab133b89_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-50ce464b740a02700915a5b205af7573ab133b89_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-50ce464b740a02700915a5b205af7573ab133b89_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-50ce464b740a02700915a5b205af7573ab133b89_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-55754642815310d1839c33d50d80471f356fdb7d_ID             := 08-warm-go-build-vendor-cache-55754642815310d1839c33d50d80471f356fdb7d
LAYER_08-warm-go-build-vendor-cache-55754642815310d1839c33d50d80471f356fdb7d_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-55754642815310d1839c33d50d80471f356fdb7d_BASE_LAYER     := 07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a
LAYER_08-warm-go-build-vendor-cache-55754642815310d1839c33d50d80471f356fdb7d_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-55754642815310d1839c33d50d80471f356fdb7d_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-55754642815310d1839c33d50d80471f356fdb7d_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-55754642815310d1839c33d50d80471f356fdb7d
LAYER_08-warm-go-build-vendor-cache-55754642815310d1839c33d50d80471f356fdb7d_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-55754642815310d1839c33d50d80471f356fdb7d.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-55754642815310d1839c33d50d80471f356fdb7d_ID),$(LAYER_08-warm-go-build-vendor-cache-55754642815310d1839c33d50d80471f356fdb7d_TYPE),$(LAYER_08-warm-go-build-vendor-cache-55754642815310d1839c33d50d80471f356fdb7d_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-55754642815310d1839c33d50d80471f356fdb7d_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-55754642815310d1839c33d50d80471f356fdb7d_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-55754642815310d1839c33d50d80471f356fdb7d_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-55754642815310d1839c33d50d80471f356fdb7d_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-5998c44a5209d09ef9fb9b13eba71bf3b59f43ee_ID             := 08-warm-go-build-vendor-cache-5998c44a5209d09ef9fb9b13eba71bf3b59f43ee
LAYER_08-warm-go-build-vendor-cache-5998c44a5209d09ef9fb9b13eba71bf3b59f43ee_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-5998c44a5209d09ef9fb9b13eba71bf3b59f43ee_BASE_LAYER     := 07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a
LAYER_08-warm-go-build-vendor-cache-5998c44a5209d09ef9fb9b13eba71bf3b59f43ee_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-5998c44a5209d09ef9fb9b13eba71bf3b59f43ee_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-5998c44a5209d09ef9fb9b13eba71bf3b59f43ee_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-5998c44a5209d09ef9fb9b13eba71bf3b59f43ee
LAYER_08-warm-go-build-vendor-cache-5998c44a5209d09ef9fb9b13eba71bf3b59f43ee_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-5998c44a5209d09ef9fb9b13eba71bf3b59f43ee.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-5998c44a5209d09ef9fb9b13eba71bf3b59f43ee_ID),$(LAYER_08-warm-go-build-vendor-cache-5998c44a5209d09ef9fb9b13eba71bf3b59f43ee_TYPE),$(LAYER_08-warm-go-build-vendor-cache-5998c44a5209d09ef9fb9b13eba71bf3b59f43ee_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-5998c44a5209d09ef9fb9b13eba71bf3b59f43ee_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-5998c44a5209d09ef9fb9b13eba71bf3b59f43ee_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-5998c44a5209d09ef9fb9b13eba71bf3b59f43ee_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-5998c44a5209d09ef9fb9b13eba71bf3b59f43ee_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-5ec19c11a2da0dbfca6fe6f803604794ebf56387_ID             := 08-warm-go-build-vendor-cache-5ec19c11a2da0dbfca6fe6f803604794ebf56387
LAYER_08-warm-go-build-vendor-cache-5ec19c11a2da0dbfca6fe6f803604794ebf56387_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-5ec19c11a2da0dbfca6fe6f803604794ebf56387_BASE_LAYER     := 07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a
LAYER_08-warm-go-build-vendor-cache-5ec19c11a2da0dbfca6fe6f803604794ebf56387_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-5ec19c11a2da0dbfca6fe6f803604794ebf56387_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-5ec19c11a2da0dbfca6fe6f803604794ebf56387_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-5ec19c11a2da0dbfca6fe6f803604794ebf56387
LAYER_08-warm-go-build-vendor-cache-5ec19c11a2da0dbfca6fe6f803604794ebf56387_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-5ec19c11a2da0dbfca6fe6f803604794ebf56387.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-5ec19c11a2da0dbfca6fe6f803604794ebf56387_ID),$(LAYER_08-warm-go-build-vendor-cache-5ec19c11a2da0dbfca6fe6f803604794ebf56387_TYPE),$(LAYER_08-warm-go-build-vendor-cache-5ec19c11a2da0dbfca6fe6f803604794ebf56387_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-5ec19c11a2da0dbfca6fe6f803604794ebf56387_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-5ec19c11a2da0dbfca6fe6f803604794ebf56387_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-5ec19c11a2da0dbfca6fe6f803604794ebf56387_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-5ec19c11a2da0dbfca6fe6f803604794ebf56387_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-66694b5c4ddf8255367cda591dc858634219df9d_ID             := 08-warm-go-build-vendor-cache-66694b5c4ddf8255367cda591dc858634219df9d
LAYER_08-warm-go-build-vendor-cache-66694b5c4ddf8255367cda591dc858634219df9d_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-66694b5c4ddf8255367cda591dc858634219df9d_BASE_LAYER     := 07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a
LAYER_08-warm-go-build-vendor-cache-66694b5c4ddf8255367cda591dc858634219df9d_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-66694b5c4ddf8255367cda591dc858634219df9d_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-66694b5c4ddf8255367cda591dc858634219df9d_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-66694b5c4ddf8255367cda591dc858634219df9d
LAYER_08-warm-go-build-vendor-cache-66694b5c4ddf8255367cda591dc858634219df9d_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-66694b5c4ddf8255367cda591dc858634219df9d.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-66694b5c4ddf8255367cda591dc858634219df9d_ID),$(LAYER_08-warm-go-build-vendor-cache-66694b5c4ddf8255367cda591dc858634219df9d_TYPE),$(LAYER_08-warm-go-build-vendor-cache-66694b5c4ddf8255367cda591dc858634219df9d_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-66694b5c4ddf8255367cda591dc858634219df9d_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-66694b5c4ddf8255367cda591dc858634219df9d_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-66694b5c4ddf8255367cda591dc858634219df9d_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-66694b5c4ddf8255367cda591dc858634219df9d_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-a89fbf761d28d56f058553cfcaa2ea7e1ab323b6_ID             := 08-warm-go-build-vendor-cache-a89fbf761d28d56f058553cfcaa2ea7e1ab323b6
LAYER_08-warm-go-build-vendor-cache-a89fbf761d28d56f058553cfcaa2ea7e1ab323b6_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-a89fbf761d28d56f058553cfcaa2ea7e1ab323b6_BASE_LAYER     := 07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a
LAYER_08-warm-go-build-vendor-cache-a89fbf761d28d56f058553cfcaa2ea7e1ab323b6_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-a89fbf761d28d56f058553cfcaa2ea7e1ab323b6_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-a89fbf761d28d56f058553cfcaa2ea7e1ab323b6_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-a89fbf761d28d56f058553cfcaa2ea7e1ab323b6
LAYER_08-warm-go-build-vendor-cache-a89fbf761d28d56f058553cfcaa2ea7e1ab323b6_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-a89fbf761d28d56f058553cfcaa2ea7e1ab323b6.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-a89fbf761d28d56f058553cfcaa2ea7e1ab323b6_ID),$(LAYER_08-warm-go-build-vendor-cache-a89fbf761d28d56f058553cfcaa2ea7e1ab323b6_TYPE),$(LAYER_08-warm-go-build-vendor-cache-a89fbf761d28d56f058553cfcaa2ea7e1ab323b6_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-a89fbf761d28d56f058553cfcaa2ea7e1ab323b6_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-a89fbf761d28d56f058553cfcaa2ea7e1ab323b6_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-a89fbf761d28d56f058553cfcaa2ea7e1ab323b6_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-a89fbf761d28d56f058553cfcaa2ea7e1ab323b6_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-cd8a1b21c4007dfbc21da039efd4eec93a3239b7_ID             := 08-warm-go-build-vendor-cache-cd8a1b21c4007dfbc21da039efd4eec93a3239b7
LAYER_08-warm-go-build-vendor-cache-cd8a1b21c4007dfbc21da039efd4eec93a3239b7_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-cd8a1b21c4007dfbc21da039efd4eec93a3239b7_BASE_LAYER     := 07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a
LAYER_08-warm-go-build-vendor-cache-cd8a1b21c4007dfbc21da039efd4eec93a3239b7_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-cd8a1b21c4007dfbc21da039efd4eec93a3239b7_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-cd8a1b21c4007dfbc21da039efd4eec93a3239b7_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-cd8a1b21c4007dfbc21da039efd4eec93a3239b7
LAYER_08-warm-go-build-vendor-cache-cd8a1b21c4007dfbc21da039efd4eec93a3239b7_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-cd8a1b21c4007dfbc21da039efd4eec93a3239b7.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-cd8a1b21c4007dfbc21da039efd4eec93a3239b7_ID),$(LAYER_08-warm-go-build-vendor-cache-cd8a1b21c4007dfbc21da039efd4eec93a3239b7_TYPE),$(LAYER_08-warm-go-build-vendor-cache-cd8a1b21c4007dfbc21da039efd4eec93a3239b7_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-cd8a1b21c4007dfbc21da039efd4eec93a3239b7_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-cd8a1b21c4007dfbc21da039efd4eec93a3239b7_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-cd8a1b21c4007dfbc21da039efd4eec93a3239b7_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-cd8a1b21c4007dfbc21da039efd4eec93a3239b7_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-db74c59d700bbd21f4dc1621a36a0e2281e2d971_ID             := 08-warm-go-build-vendor-cache-db74c59d700bbd21f4dc1621a36a0e2281e2d971
LAYER_08-warm-go-build-vendor-cache-db74c59d700bbd21f4dc1621a36a0e2281e2d971_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-db74c59d700bbd21f4dc1621a36a0e2281e2d971_BASE_LAYER     := 07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a
LAYER_08-warm-go-build-vendor-cache-db74c59d700bbd21f4dc1621a36a0e2281e2d971_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-db74c59d700bbd21f4dc1621a36a0e2281e2d971_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-db74c59d700bbd21f4dc1621a36a0e2281e2d971_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-db74c59d700bbd21f4dc1621a36a0e2281e2d971
LAYER_08-warm-go-build-vendor-cache-db74c59d700bbd21f4dc1621a36a0e2281e2d971_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-db74c59d700bbd21f4dc1621a36a0e2281e2d971.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-db74c59d700bbd21f4dc1621a36a0e2281e2d971_ID),$(LAYER_08-warm-go-build-vendor-cache-db74c59d700bbd21f4dc1621a36a0e2281e2d971_TYPE),$(LAYER_08-warm-go-build-vendor-cache-db74c59d700bbd21f4dc1621a36a0e2281e2d971_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-db74c59d700bbd21f4dc1621a36a0e2281e2d971_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-db74c59d700bbd21f4dc1621a36a0e2281e2d971_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-db74c59d700bbd21f4dc1621a36a0e2281e2d971_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-db74c59d700bbd21f4dc1621a36a0e2281e2d971_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-dbd41e8cb9b8f1c4f7cb4515a463cda59234830b_ID             := 08-warm-go-build-vendor-cache-dbd41e8cb9b8f1c4f7cb4515a463cda59234830b
LAYER_08-warm-go-build-vendor-cache-dbd41e8cb9b8f1c4f7cb4515a463cda59234830b_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-dbd41e8cb9b8f1c4f7cb4515a463cda59234830b_BASE_LAYER     := 07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a
LAYER_08-warm-go-build-vendor-cache-dbd41e8cb9b8f1c4f7cb4515a463cda59234830b_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-dbd41e8cb9b8f1c4f7cb4515a463cda59234830b_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-dbd41e8cb9b8f1c4f7cb4515a463cda59234830b_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-dbd41e8cb9b8f1c4f7cb4515a463cda59234830b
LAYER_08-warm-go-build-vendor-cache-dbd41e8cb9b8f1c4f7cb4515a463cda59234830b_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-dbd41e8cb9b8f1c4f7cb4515a463cda59234830b.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-dbd41e8cb9b8f1c4f7cb4515a463cda59234830b_ID),$(LAYER_08-warm-go-build-vendor-cache-dbd41e8cb9b8f1c4f7cb4515a463cda59234830b_TYPE),$(LAYER_08-warm-go-build-vendor-cache-dbd41e8cb9b8f1c4f7cb4515a463cda59234830b_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-dbd41e8cb9b8f1c4f7cb4515a463cda59234830b_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-dbd41e8cb9b8f1c4f7cb4515a463cda59234830b_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-dbd41e8cb9b8f1c4f7cb4515a463cda59234830b_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-dbd41e8cb9b8f1c4f7cb4515a463cda59234830b_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-fc634901882d94ecd546983a4c48060c36d92af3_ID             := 08-warm-go-build-vendor-cache-fc634901882d94ecd546983a4c48060c36d92af3
LAYER_08-warm-go-build-vendor-cache-fc634901882d94ecd546983a4c48060c36d92af3_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-fc634901882d94ecd546983a4c48060c36d92af3_BASE_LAYER     := 07-build-static-assets-543db80681a157cc7cad64884b4ca8cd01310a0a
LAYER_08-warm-go-build-vendor-cache-fc634901882d94ecd546983a4c48060c36d92af3_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-fc634901882d94ecd546983a4c48060c36d92af3_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-fc634901882d94ecd546983a4c48060c36d92af3_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-fc634901882d94ecd546983a4c48060c36d92af3
LAYER_08-warm-go-build-vendor-cache-fc634901882d94ecd546983a4c48060c36d92af3_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-fc634901882d94ecd546983a4c48060c36d92af3.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-fc634901882d94ecd546983a4c48060c36d92af3_ID),$(LAYER_08-warm-go-build-vendor-cache-fc634901882d94ecd546983a4c48060c36d92af3_TYPE),$(LAYER_08-warm-go-build-vendor-cache-fc634901882d94ecd546983a4c48060c36d92af3_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-fc634901882d94ecd546983a4c48060c36d92af3_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-fc634901882d94ecd546983a4c48060c36d92af3_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-fc634901882d94ecd546983a4c48060c36d92af3_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-fc634901882d94ecd546983a4c48060c36d92af3_ARCHIVE_FILE)))

LAYER_09-copy-source-20e0f234d082b458301a8fff79711311e208e70d_ID             := 09-copy-source-20e0f234d082b458301a8fff79711311e208e70d
LAYER_09-copy-source-20e0f234d082b458301a8fff79711311e208e70d_TYPE           := copy-source
LAYER_09-copy-source-20e0f234d082b458301a8fff79711311e208e70d_BASE_LAYER     := 08-warm-go-build-vendor-cache-5ec19c11a2da0dbfca6fe6f803604794ebf56387
LAYER_09-copy-source-20e0f234d082b458301a8fff79711311e208e70d_SOURCE_INCLUDE := .
LAYER_09-copy-source-20e0f234d082b458301a8fff79711311e208e70d_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-20e0f234d082b458301a8fff79711311e208e70d_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-20e0f234d082b458301a8fff79711311e208e70d
LAYER_09-copy-source-20e0f234d082b458301a8fff79711311e208e70d_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-20e0f234d082b458301a8fff79711311e208e70d.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-20e0f234d082b458301a8fff79711311e208e70d_ID),$(LAYER_09-copy-source-20e0f234d082b458301a8fff79711311e208e70d_TYPE),$(LAYER_09-copy-source-20e0f234d082b458301a8fff79711311e208e70d_BASE_LAYER),$(LAYER_09-copy-source-20e0f234d082b458301a8fff79711311e208e70d_SOURCE_INCLUDE),$(LAYER_09-copy-source-20e0f234d082b458301a8fff79711311e208e70d_SOURCE_EXCLUDE),$(LAYER_09-copy-source-20e0f234d082b458301a8fff79711311e208e70d_CACHE_KEY_FILE),$(LAYER_09-copy-source-20e0f234d082b458301a8fff79711311e208e70d_ARCHIVE_FILE)))

LAYER_09-copy-source-267482d0d1c908f8e80281e1e3066a5061f53e2f_ID             := 09-copy-source-267482d0d1c908f8e80281e1e3066a5061f53e2f
LAYER_09-copy-source-267482d0d1c908f8e80281e1e3066a5061f53e2f_TYPE           := copy-source
LAYER_09-copy-source-267482d0d1c908f8e80281e1e3066a5061f53e2f_BASE_LAYER     := 08-warm-go-build-vendor-cache-2c63ea8cc70c02b080c15ea409277e4444eda586
LAYER_09-copy-source-267482d0d1c908f8e80281e1e3066a5061f53e2f_SOURCE_INCLUDE := .
LAYER_09-copy-source-267482d0d1c908f8e80281e1e3066a5061f53e2f_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-267482d0d1c908f8e80281e1e3066a5061f53e2f_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-267482d0d1c908f8e80281e1e3066a5061f53e2f
LAYER_09-copy-source-267482d0d1c908f8e80281e1e3066a5061f53e2f_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-267482d0d1c908f8e80281e1e3066a5061f53e2f.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-267482d0d1c908f8e80281e1e3066a5061f53e2f_ID),$(LAYER_09-copy-source-267482d0d1c908f8e80281e1e3066a5061f53e2f_TYPE),$(LAYER_09-copy-source-267482d0d1c908f8e80281e1e3066a5061f53e2f_BASE_LAYER),$(LAYER_09-copy-source-267482d0d1c908f8e80281e1e3066a5061f53e2f_SOURCE_INCLUDE),$(LAYER_09-copy-source-267482d0d1c908f8e80281e1e3066a5061f53e2f_SOURCE_EXCLUDE),$(LAYER_09-copy-source-267482d0d1c908f8e80281e1e3066a5061f53e2f_CACHE_KEY_FILE),$(LAYER_09-copy-source-267482d0d1c908f8e80281e1e3066a5061f53e2f_ARCHIVE_FILE)))

LAYER_09-copy-source-54c65a1981e885ce7a504ec2fa713dc9e7914fb8_ID             := 09-copy-source-54c65a1981e885ce7a504ec2fa713dc9e7914fb8
LAYER_09-copy-source-54c65a1981e885ce7a504ec2fa713dc9e7914fb8_TYPE           := copy-source
LAYER_09-copy-source-54c65a1981e885ce7a504ec2fa713dc9e7914fb8_BASE_LAYER     := 08-warm-go-build-vendor-cache-55754642815310d1839c33d50d80471f356fdb7d
LAYER_09-copy-source-54c65a1981e885ce7a504ec2fa713dc9e7914fb8_SOURCE_INCLUDE := .
LAYER_09-copy-source-54c65a1981e885ce7a504ec2fa713dc9e7914fb8_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-54c65a1981e885ce7a504ec2fa713dc9e7914fb8_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-54c65a1981e885ce7a504ec2fa713dc9e7914fb8
LAYER_09-copy-source-54c65a1981e885ce7a504ec2fa713dc9e7914fb8_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-54c65a1981e885ce7a504ec2fa713dc9e7914fb8.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-54c65a1981e885ce7a504ec2fa713dc9e7914fb8_ID),$(LAYER_09-copy-source-54c65a1981e885ce7a504ec2fa713dc9e7914fb8_TYPE),$(LAYER_09-copy-source-54c65a1981e885ce7a504ec2fa713dc9e7914fb8_BASE_LAYER),$(LAYER_09-copy-source-54c65a1981e885ce7a504ec2fa713dc9e7914fb8_SOURCE_INCLUDE),$(LAYER_09-copy-source-54c65a1981e885ce7a504ec2fa713dc9e7914fb8_SOURCE_EXCLUDE),$(LAYER_09-copy-source-54c65a1981e885ce7a504ec2fa713dc9e7914fb8_CACHE_KEY_FILE),$(LAYER_09-copy-source-54c65a1981e885ce7a504ec2fa713dc9e7914fb8_ARCHIVE_FILE)))

LAYER_09-copy-source-5cca98a82f54603200f4d462356c6f9bce63ae2f_ID             := 09-copy-source-5cca98a82f54603200f4d462356c6f9bce63ae2f
LAYER_09-copy-source-5cca98a82f54603200f4d462356c6f9bce63ae2f_TYPE           := copy-source
LAYER_09-copy-source-5cca98a82f54603200f4d462356c6f9bce63ae2f_BASE_LAYER     := 08-warm-go-build-vendor-cache-23a6c6f7a369ed9e9975e4e24f3c8f01c83ea162
LAYER_09-copy-source-5cca98a82f54603200f4d462356c6f9bce63ae2f_SOURCE_INCLUDE := .
LAYER_09-copy-source-5cca98a82f54603200f4d462356c6f9bce63ae2f_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-5cca98a82f54603200f4d462356c6f9bce63ae2f_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-5cca98a82f54603200f4d462356c6f9bce63ae2f
LAYER_09-copy-source-5cca98a82f54603200f4d462356c6f9bce63ae2f_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-5cca98a82f54603200f4d462356c6f9bce63ae2f.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-5cca98a82f54603200f4d462356c6f9bce63ae2f_ID),$(LAYER_09-copy-source-5cca98a82f54603200f4d462356c6f9bce63ae2f_TYPE),$(LAYER_09-copy-source-5cca98a82f54603200f4d462356c6f9bce63ae2f_BASE_LAYER),$(LAYER_09-copy-source-5cca98a82f54603200f4d462356c6f9bce63ae2f_SOURCE_INCLUDE),$(LAYER_09-copy-source-5cca98a82f54603200f4d462356c6f9bce63ae2f_SOURCE_EXCLUDE),$(LAYER_09-copy-source-5cca98a82f54603200f4d462356c6f9bce63ae2f_CACHE_KEY_FILE),$(LAYER_09-copy-source-5cca98a82f54603200f4d462356c6f9bce63ae2f_ARCHIVE_FILE)))

LAYER_09-copy-source-611f652a87e665d3e816c30b5a051f499ff9e44a_ID             := 09-copy-source-611f652a87e665d3e816c30b5a051f499ff9e44a
LAYER_09-copy-source-611f652a87e665d3e816c30b5a051f499ff9e44a_TYPE           := copy-source
LAYER_09-copy-source-611f652a87e665d3e816c30b5a051f499ff9e44a_BASE_LAYER     := 08-warm-go-build-vendor-cache-cd8a1b21c4007dfbc21da039efd4eec93a3239b7
LAYER_09-copy-source-611f652a87e665d3e816c30b5a051f499ff9e44a_SOURCE_INCLUDE := .
LAYER_09-copy-source-611f652a87e665d3e816c30b5a051f499ff9e44a_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-611f652a87e665d3e816c30b5a051f499ff9e44a_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-611f652a87e665d3e816c30b5a051f499ff9e44a
LAYER_09-copy-source-611f652a87e665d3e816c30b5a051f499ff9e44a_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-611f652a87e665d3e816c30b5a051f499ff9e44a.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-611f652a87e665d3e816c30b5a051f499ff9e44a_ID),$(LAYER_09-copy-source-611f652a87e665d3e816c30b5a051f499ff9e44a_TYPE),$(LAYER_09-copy-source-611f652a87e665d3e816c30b5a051f499ff9e44a_BASE_LAYER),$(LAYER_09-copy-source-611f652a87e665d3e816c30b5a051f499ff9e44a_SOURCE_INCLUDE),$(LAYER_09-copy-source-611f652a87e665d3e816c30b5a051f499ff9e44a_SOURCE_EXCLUDE),$(LAYER_09-copy-source-611f652a87e665d3e816c30b5a051f499ff9e44a_CACHE_KEY_FILE),$(LAYER_09-copy-source-611f652a87e665d3e816c30b5a051f499ff9e44a_ARCHIVE_FILE)))

LAYER_09-copy-source-85ba809525e8c2e766b186a50c8f0834c470ae87_ID             := 09-copy-source-85ba809525e8c2e766b186a50c8f0834c470ae87
LAYER_09-copy-source-85ba809525e8c2e766b186a50c8f0834c470ae87_TYPE           := copy-source
LAYER_09-copy-source-85ba809525e8c2e766b186a50c8f0834c470ae87_BASE_LAYER     := 08-warm-go-build-vendor-cache-fc634901882d94ecd546983a4c48060c36d92af3
LAYER_09-copy-source-85ba809525e8c2e766b186a50c8f0834c470ae87_SOURCE_INCLUDE := .
LAYER_09-copy-source-85ba809525e8c2e766b186a50c8f0834c470ae87_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-85ba809525e8c2e766b186a50c8f0834c470ae87_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-85ba809525e8c2e766b186a50c8f0834c470ae87
LAYER_09-copy-source-85ba809525e8c2e766b186a50c8f0834c470ae87_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-85ba809525e8c2e766b186a50c8f0834c470ae87.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-85ba809525e8c2e766b186a50c8f0834c470ae87_ID),$(LAYER_09-copy-source-85ba809525e8c2e766b186a50c8f0834c470ae87_TYPE),$(LAYER_09-copy-source-85ba809525e8c2e766b186a50c8f0834c470ae87_BASE_LAYER),$(LAYER_09-copy-source-85ba809525e8c2e766b186a50c8f0834c470ae87_SOURCE_INCLUDE),$(LAYER_09-copy-source-85ba809525e8c2e766b186a50c8f0834c470ae87_SOURCE_EXCLUDE),$(LAYER_09-copy-source-85ba809525e8c2e766b186a50c8f0834c470ae87_CACHE_KEY_FILE),$(LAYER_09-copy-source-85ba809525e8c2e766b186a50c8f0834c470ae87_ARCHIVE_FILE)))

LAYER_09-copy-source-98be26fc6f1de09f1cbb665be00921e414a6ee0b_ID             := 09-copy-source-98be26fc6f1de09f1cbb665be00921e414a6ee0b
LAYER_09-copy-source-98be26fc6f1de09f1cbb665be00921e414a6ee0b_TYPE           := copy-source
LAYER_09-copy-source-98be26fc6f1de09f1cbb665be00921e414a6ee0b_BASE_LAYER     := 08-warm-go-build-vendor-cache-5998c44a5209d09ef9fb9b13eba71bf3b59f43ee
LAYER_09-copy-source-98be26fc6f1de09f1cbb665be00921e414a6ee0b_SOURCE_INCLUDE := .
LAYER_09-copy-source-98be26fc6f1de09f1cbb665be00921e414a6ee0b_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-98be26fc6f1de09f1cbb665be00921e414a6ee0b_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-98be26fc6f1de09f1cbb665be00921e414a6ee0b
LAYER_09-copy-source-98be26fc6f1de09f1cbb665be00921e414a6ee0b_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-98be26fc6f1de09f1cbb665be00921e414a6ee0b.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-98be26fc6f1de09f1cbb665be00921e414a6ee0b_ID),$(LAYER_09-copy-source-98be26fc6f1de09f1cbb665be00921e414a6ee0b_TYPE),$(LAYER_09-copy-source-98be26fc6f1de09f1cbb665be00921e414a6ee0b_BASE_LAYER),$(LAYER_09-copy-source-98be26fc6f1de09f1cbb665be00921e414a6ee0b_SOURCE_INCLUDE),$(LAYER_09-copy-source-98be26fc6f1de09f1cbb665be00921e414a6ee0b_SOURCE_EXCLUDE),$(LAYER_09-copy-source-98be26fc6f1de09f1cbb665be00921e414a6ee0b_CACHE_KEY_FILE),$(LAYER_09-copy-source-98be26fc6f1de09f1cbb665be00921e414a6ee0b_ARCHIVE_FILE)))

LAYER_09-copy-source-99da2a693c90e31b926fda0e83cfacf9430330d9_ID             := 09-copy-source-99da2a693c90e31b926fda0e83cfacf9430330d9
LAYER_09-copy-source-99da2a693c90e31b926fda0e83cfacf9430330d9_TYPE           := copy-source
LAYER_09-copy-source-99da2a693c90e31b926fda0e83cfacf9430330d9_BASE_LAYER     := 08-warm-go-build-vendor-cache-66694b5c4ddf8255367cda591dc858634219df9d
LAYER_09-copy-source-99da2a693c90e31b926fda0e83cfacf9430330d9_SOURCE_INCLUDE := .
LAYER_09-copy-source-99da2a693c90e31b926fda0e83cfacf9430330d9_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-99da2a693c90e31b926fda0e83cfacf9430330d9_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-99da2a693c90e31b926fda0e83cfacf9430330d9
LAYER_09-copy-source-99da2a693c90e31b926fda0e83cfacf9430330d9_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-99da2a693c90e31b926fda0e83cfacf9430330d9.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-99da2a693c90e31b926fda0e83cfacf9430330d9_ID),$(LAYER_09-copy-source-99da2a693c90e31b926fda0e83cfacf9430330d9_TYPE),$(LAYER_09-copy-source-99da2a693c90e31b926fda0e83cfacf9430330d9_BASE_LAYER),$(LAYER_09-copy-source-99da2a693c90e31b926fda0e83cfacf9430330d9_SOURCE_INCLUDE),$(LAYER_09-copy-source-99da2a693c90e31b926fda0e83cfacf9430330d9_SOURCE_EXCLUDE),$(LAYER_09-copy-source-99da2a693c90e31b926fda0e83cfacf9430330d9_CACHE_KEY_FILE),$(LAYER_09-copy-source-99da2a693c90e31b926fda0e83cfacf9430330d9_ARCHIVE_FILE)))

LAYER_09-copy-source-ab93d8526b028672581b6f2fea0632bebea3be44_ID             := 09-copy-source-ab93d8526b028672581b6f2fea0632bebea3be44
LAYER_09-copy-source-ab93d8526b028672581b6f2fea0632bebea3be44_TYPE           := copy-source
LAYER_09-copy-source-ab93d8526b028672581b6f2fea0632bebea3be44_BASE_LAYER     := 08-warm-go-build-vendor-cache-a89fbf761d28d56f058553cfcaa2ea7e1ab323b6
LAYER_09-copy-source-ab93d8526b028672581b6f2fea0632bebea3be44_SOURCE_INCLUDE := .
LAYER_09-copy-source-ab93d8526b028672581b6f2fea0632bebea3be44_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-ab93d8526b028672581b6f2fea0632bebea3be44_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-ab93d8526b028672581b6f2fea0632bebea3be44
LAYER_09-copy-source-ab93d8526b028672581b6f2fea0632bebea3be44_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-ab93d8526b028672581b6f2fea0632bebea3be44.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-ab93d8526b028672581b6f2fea0632bebea3be44_ID),$(LAYER_09-copy-source-ab93d8526b028672581b6f2fea0632bebea3be44_TYPE),$(LAYER_09-copy-source-ab93d8526b028672581b6f2fea0632bebea3be44_BASE_LAYER),$(LAYER_09-copy-source-ab93d8526b028672581b6f2fea0632bebea3be44_SOURCE_INCLUDE),$(LAYER_09-copy-source-ab93d8526b028672581b6f2fea0632bebea3be44_SOURCE_EXCLUDE),$(LAYER_09-copy-source-ab93d8526b028672581b6f2fea0632bebea3be44_CACHE_KEY_FILE),$(LAYER_09-copy-source-ab93d8526b028672581b6f2fea0632bebea3be44_ARCHIVE_FILE)))

LAYER_09-copy-source-aee3b86247aa6a7703185d13055ec8ef0561803d_ID             := 09-copy-source-aee3b86247aa6a7703185d13055ec8ef0561803d
LAYER_09-copy-source-aee3b86247aa6a7703185d13055ec8ef0561803d_TYPE           := copy-source
LAYER_09-copy-source-aee3b86247aa6a7703185d13055ec8ef0561803d_BASE_LAYER     := 08-warm-go-build-vendor-cache-4d2cd97c46a8cbe60b8b278a7c1abead3418dbf4
LAYER_09-copy-source-aee3b86247aa6a7703185d13055ec8ef0561803d_SOURCE_INCLUDE := .
LAYER_09-copy-source-aee3b86247aa6a7703185d13055ec8ef0561803d_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-aee3b86247aa6a7703185d13055ec8ef0561803d_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-aee3b86247aa6a7703185d13055ec8ef0561803d
LAYER_09-copy-source-aee3b86247aa6a7703185d13055ec8ef0561803d_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-aee3b86247aa6a7703185d13055ec8ef0561803d.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-aee3b86247aa6a7703185d13055ec8ef0561803d_ID),$(LAYER_09-copy-source-aee3b86247aa6a7703185d13055ec8ef0561803d_TYPE),$(LAYER_09-copy-source-aee3b86247aa6a7703185d13055ec8ef0561803d_BASE_LAYER),$(LAYER_09-copy-source-aee3b86247aa6a7703185d13055ec8ef0561803d_SOURCE_INCLUDE),$(LAYER_09-copy-source-aee3b86247aa6a7703185d13055ec8ef0561803d_SOURCE_EXCLUDE),$(LAYER_09-copy-source-aee3b86247aa6a7703185d13055ec8ef0561803d_CACHE_KEY_FILE),$(LAYER_09-copy-source-aee3b86247aa6a7703185d13055ec8ef0561803d_ARCHIVE_FILE)))

LAYER_09-copy-source-b2920bf168f1d71fa2c4937c46200dd189a416b9_ID             := 09-copy-source-b2920bf168f1d71fa2c4937c46200dd189a416b9
LAYER_09-copy-source-b2920bf168f1d71fa2c4937c46200dd189a416b9_TYPE           := copy-source
LAYER_09-copy-source-b2920bf168f1d71fa2c4937c46200dd189a416b9_BASE_LAYER     := 08-warm-go-build-vendor-cache-db74c59d700bbd21f4dc1621a36a0e2281e2d971
LAYER_09-copy-source-b2920bf168f1d71fa2c4937c46200dd189a416b9_SOURCE_INCLUDE := .
LAYER_09-copy-source-b2920bf168f1d71fa2c4937c46200dd189a416b9_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-b2920bf168f1d71fa2c4937c46200dd189a416b9_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-b2920bf168f1d71fa2c4937c46200dd189a416b9
LAYER_09-copy-source-b2920bf168f1d71fa2c4937c46200dd189a416b9_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-b2920bf168f1d71fa2c4937c46200dd189a416b9.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-b2920bf168f1d71fa2c4937c46200dd189a416b9_ID),$(LAYER_09-copy-source-b2920bf168f1d71fa2c4937c46200dd189a416b9_TYPE),$(LAYER_09-copy-source-b2920bf168f1d71fa2c4937c46200dd189a416b9_BASE_LAYER),$(LAYER_09-copy-source-b2920bf168f1d71fa2c4937c46200dd189a416b9_SOURCE_INCLUDE),$(LAYER_09-copy-source-b2920bf168f1d71fa2c4937c46200dd189a416b9_SOURCE_EXCLUDE),$(LAYER_09-copy-source-b2920bf168f1d71fa2c4937c46200dd189a416b9_CACHE_KEY_FILE),$(LAYER_09-copy-source-b2920bf168f1d71fa2c4937c46200dd189a416b9_ARCHIVE_FILE)))

LAYER_09-copy-source-b5b03901413deec528c094573c73dc1dc23e3d7a_ID             := 09-copy-source-b5b03901413deec528c094573c73dc1dc23e3d7a
LAYER_09-copy-source-b5b03901413deec528c094573c73dc1dc23e3d7a_TYPE           := copy-source
LAYER_09-copy-source-b5b03901413deec528c094573c73dc1dc23e3d7a_BASE_LAYER     := 08-warm-go-build-vendor-cache-dbd41e8cb9b8f1c4f7cb4515a463cda59234830b
LAYER_09-copy-source-b5b03901413deec528c094573c73dc1dc23e3d7a_SOURCE_INCLUDE := .
LAYER_09-copy-source-b5b03901413deec528c094573c73dc1dc23e3d7a_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-b5b03901413deec528c094573c73dc1dc23e3d7a_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-b5b03901413deec528c094573c73dc1dc23e3d7a
LAYER_09-copy-source-b5b03901413deec528c094573c73dc1dc23e3d7a_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-b5b03901413deec528c094573c73dc1dc23e3d7a.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-b5b03901413deec528c094573c73dc1dc23e3d7a_ID),$(LAYER_09-copy-source-b5b03901413deec528c094573c73dc1dc23e3d7a_TYPE),$(LAYER_09-copy-source-b5b03901413deec528c094573c73dc1dc23e3d7a_BASE_LAYER),$(LAYER_09-copy-source-b5b03901413deec528c094573c73dc1dc23e3d7a_SOURCE_INCLUDE),$(LAYER_09-copy-source-b5b03901413deec528c094573c73dc1dc23e3d7a_SOURCE_EXCLUDE),$(LAYER_09-copy-source-b5b03901413deec528c094573c73dc1dc23e3d7a_CACHE_KEY_FILE),$(LAYER_09-copy-source-b5b03901413deec528c094573c73dc1dc23e3d7a_ARCHIVE_FILE)))

LAYER_09-copy-source-dab40a5d3fd2a6c3ac5280b2a1d03ec2a9ac7867_ID             := 09-copy-source-dab40a5d3fd2a6c3ac5280b2a1d03ec2a9ac7867
LAYER_09-copy-source-dab40a5d3fd2a6c3ac5280b2a1d03ec2a9ac7867_TYPE           := copy-source
LAYER_09-copy-source-dab40a5d3fd2a6c3ac5280b2a1d03ec2a9ac7867_BASE_LAYER     := 08-warm-go-build-vendor-cache-1396b381f7ea7b775f15a067617c7484766d073b
LAYER_09-copy-source-dab40a5d3fd2a6c3ac5280b2a1d03ec2a9ac7867_SOURCE_INCLUDE := .
LAYER_09-copy-source-dab40a5d3fd2a6c3ac5280b2a1d03ec2a9ac7867_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-dab40a5d3fd2a6c3ac5280b2a1d03ec2a9ac7867_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-dab40a5d3fd2a6c3ac5280b2a1d03ec2a9ac7867
LAYER_09-copy-source-dab40a5d3fd2a6c3ac5280b2a1d03ec2a9ac7867_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-dab40a5d3fd2a6c3ac5280b2a1d03ec2a9ac7867.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-dab40a5d3fd2a6c3ac5280b2a1d03ec2a9ac7867_ID),$(LAYER_09-copy-source-dab40a5d3fd2a6c3ac5280b2a1d03ec2a9ac7867_TYPE),$(LAYER_09-copy-source-dab40a5d3fd2a6c3ac5280b2a1d03ec2a9ac7867_BASE_LAYER),$(LAYER_09-copy-source-dab40a5d3fd2a6c3ac5280b2a1d03ec2a9ac7867_SOURCE_INCLUDE),$(LAYER_09-copy-source-dab40a5d3fd2a6c3ac5280b2a1d03ec2a9ac7867_SOURCE_EXCLUDE),$(LAYER_09-copy-source-dab40a5d3fd2a6c3ac5280b2a1d03ec2a9ac7867_CACHE_KEY_FILE),$(LAYER_09-copy-source-dab40a5d3fd2a6c3ac5280b2a1d03ec2a9ac7867_ARCHIVE_FILE)))

LAYER_09-copy-source-e3c3bbea85c00980aedace022014e2e477aa0c58_ID             := 09-copy-source-e3c3bbea85c00980aedace022014e2e477aa0c58
LAYER_09-copy-source-e3c3bbea85c00980aedace022014e2e477aa0c58_TYPE           := copy-source
LAYER_09-copy-source-e3c3bbea85c00980aedace022014e2e477aa0c58_BASE_LAYER     := 08-warm-go-build-vendor-cache-09d209869ea8d7ec24075af621821444526443f4
LAYER_09-copy-source-e3c3bbea85c00980aedace022014e2e477aa0c58_SOURCE_INCLUDE := .
LAYER_09-copy-source-e3c3bbea85c00980aedace022014e2e477aa0c58_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-e3c3bbea85c00980aedace022014e2e477aa0c58_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-e3c3bbea85c00980aedace022014e2e477aa0c58
LAYER_09-copy-source-e3c3bbea85c00980aedace022014e2e477aa0c58_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-e3c3bbea85c00980aedace022014e2e477aa0c58.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-e3c3bbea85c00980aedace022014e2e477aa0c58_ID),$(LAYER_09-copy-source-e3c3bbea85c00980aedace022014e2e477aa0c58_TYPE),$(LAYER_09-copy-source-e3c3bbea85c00980aedace022014e2e477aa0c58_BASE_LAYER),$(LAYER_09-copy-source-e3c3bbea85c00980aedace022014e2e477aa0c58_SOURCE_INCLUDE),$(LAYER_09-copy-source-e3c3bbea85c00980aedace022014e2e477aa0c58_SOURCE_EXCLUDE),$(LAYER_09-copy-source-e3c3bbea85c00980aedace022014e2e477aa0c58_CACHE_KEY_FILE),$(LAYER_09-copy-source-e3c3bbea85c00980aedace022014e2e477aa0c58_ARCHIVE_FILE)))

LAYER_09-copy-source-e762427214d549a0f2a8954e05e84b9469fcfa3f_ID             := 09-copy-source-e762427214d549a0f2a8954e05e84b9469fcfa3f
LAYER_09-copy-source-e762427214d549a0f2a8954e05e84b9469fcfa3f_TYPE           := copy-source
LAYER_09-copy-source-e762427214d549a0f2a8954e05e84b9469fcfa3f_BASE_LAYER     := 08-warm-go-build-vendor-cache-50ce464b740a02700915a5b205af7573ab133b89
LAYER_09-copy-source-e762427214d549a0f2a8954e05e84b9469fcfa3f_SOURCE_INCLUDE := .
LAYER_09-copy-source-e762427214d549a0f2a8954e05e84b9469fcfa3f_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-e762427214d549a0f2a8954e05e84b9469fcfa3f_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-e762427214d549a0f2a8954e05e84b9469fcfa3f
LAYER_09-copy-source-e762427214d549a0f2a8954e05e84b9469fcfa3f_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-e762427214d549a0f2a8954e05e84b9469fcfa3f.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-e762427214d549a0f2a8954e05e84b9469fcfa3f_ID),$(LAYER_09-copy-source-e762427214d549a0f2a8954e05e84b9469fcfa3f_TYPE),$(LAYER_09-copy-source-e762427214d549a0f2a8954e05e84b9469fcfa3f_BASE_LAYER),$(LAYER_09-copy-source-e762427214d549a0f2a8954e05e84b9469fcfa3f_SOURCE_INCLUDE),$(LAYER_09-copy-source-e762427214d549a0f2a8954e05e84b9469fcfa3f_SOURCE_EXCLUDE),$(LAYER_09-copy-source-e762427214d549a0f2a8954e05e84b9469fcfa3f_CACHE_KEY_FILE),$(LAYER_09-copy-source-e762427214d549a0f2a8954e05e84b9469fcfa3f_ARCHIVE_FILE)))
